name: std_ass
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
 # hive: ^2.0.4
 # hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.0.1
  percent_indicator: ^4.2.3
  flutter_heatmap_calendar: ^1.0.5
  path_provider: ^2.0.4
  cloud_firestore: ^4.13.3
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  google_fonts: ^6.1.0
  #simple_animations: ^5.0.2
  provider: ^6.0.2
  fl_chart: ^0.45.0
  #flutter_slidable: ^1.2.0
  sqflite: ^2.0.2
  simple_animations: ^5.0.2
  #simple_animations: ^4.0.1
  # path_provider: ^2.0.9
  supercharged: ^2.1.1
  animate_do: ^3.1.2
  #shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.6.0 
  flutter_launcher_icons: ^0.13.1
  page_transition: ^2.0.5 
  #animated_builder: ^5.0.0
  msh_checkbox: ^2.0.1 
  uuid: ^4.2.1
  intl: ^0.18.1
  #sqflite: ^1.1.7
  toast: ^0.1.5
  url_launcher: ^6.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive: ^2.2.3
  # hive_flutter: ^1.1.0
  # hive_generator: ^2.0.1
  build_runner: ^2.4.6
  cloud_firestore: ^4.13.3
  flutter_lints: ^3.0.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/slide_two.json
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
